site_name: "TorchSystem" 
  
theme:
  name: material
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate 
    - content.code.highlight


markdown_extensions:
  - pymdownx.highlight:
      pygments_style: default
  - pymdownx.superfences
  - pymdownx.inlinehilite

plugins:
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: "google" 

nav:
  - Home: index.md
  - Domain: domain.md
  - Registry: registry.md
  - Dependency Injection: depends.md
  - Compiler: compiler.md
  - Services: services.md
  - Producer/Consumer: prodcon.md
  - Publisher/Subscriber: pubsub.md