name: CI
on:
  push:
    paths:
      - '**/*.py'  
      - 'torchsystem/**' 
      - 'tests/**' 
      
  pull_request:
    paths:
      - '**/*.py' 
      - 'torchsystem/**'   
      - 'tests/**'   

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
        - uses: actions/checkout@v4
        - name: Set up Python 3.12
          uses: actions/setup-python@v3
          with:
            python-version: ${{ matrix.python-version }}

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install flake8 pytest
            pip install mlregistry
            pip install pybondi
            pip install pydantic-settings
            
        - name: Install torch dependency for Linux (Ubuntu)
          if: matrix.os == 'ubuntu-latest'
          run: pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu

        - name: Install dependencies for macOS
          if: matrix.os == 'macos-latest'
          run: pip3 install torch torchvision torchaudio

        - name: Install dependencies for Windows
          if: matrix.os == 'windows-latest'
          run: pip3 install torch torchvision torchaudio

        - name: Test with pytest
          run: |
            pytest