name: CI
on: [push, pull_request]

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
        poetry-version: ["latest", "1.8.3"]
        os: [ubuntu-22.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
        - uses: actions/checkout@v4
        - name: Set up Python 3.12
          uses: actions/setup-python@v3
          with:
            python-version: ${{ matrix.python-version }}
                      
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install flake8 pytest
            pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
            pip install mlregistry
            pip install pybondi

        - name: Test with pytest
          run: |
            pytest